packages:
  - examples/next
  - examples/node
  - examples/svelte
  - packages/*
catalog:
  "@cartridge/controller-wasm": "^0.2.7"
  "@cartridge/penpal": "^6.2.4"
  "@cartridge/ui": "github:cartridge-gg/ui#35c6c82"
  "@eslint/js": "^9.18.0"
  "@noble/curves": "^1.9.0"
  "@noble/hashes": "^1.8.0"
  "@dojoengine/core": "^1.6.0"
  "@dojoengine/torii-wasm": "^1.6.0"
  "@starknet-io/types-js": "^0.8.4"
  "@starknet-react/chains": "4.0.1-beta.3"
  "@starknet-react/core": "4.0.1-beta.4"
  "@storybook/addon-essentials": "^8.5.0"
  "@storybook/addon-themes": "^8.5.0"
  "@storybook/blocks": "^8.5.0"
  "@storybook/react": "^8.5.0"
  "@storybook/react-vite": "^8.5.0"
  "@storybook/test": "^8.5.0"
  "@storybook/test-runner": "^0.21.0"
  "@storybook/theming": "^8.5.0"
  "@types/jest-image-snapshot": "^6.4.0"
  "@types/lodash": "^4.17.14"
  "@types/node": "^18.0.6"
  "@types/react": "^18.2.0"
  "@types/react-dom": "^18.2.0"
  "@types/jest": "^29.5.14"
  "@types/mocha": "^10.0.10"
  "@vitejs/plugin-react-swc": "^3.5.0"
  "@solana/spl-token": "^0.4.13"
  "@solana/web3.js": "^1.98.0"
  autoprefixer: "^10.4.18"
  base64url: "^3.0.1"
  eslint: "^9.12.0"
  fast-deep-equal: "^3.1.3"
  globals: "^15.0.0"
  http-server: "^14.1.1"
  jest-image-snapshot: "^6.4.0"
  lodash: "^4.17.21"
  playwright: "^1.49.1"
  postcss: "^8.4.35"
  postcss-import: "^16.1.0"
  prettier: "^3.4.2"
  react: "^18.2.0"
  react-dom: "^18.2.0"
  react-query: "^3.39.2"
  react-router-dom: "^6.27.0"
  sonner: "^1.4.41"
  start-server-and-test: "^2.0.9"
  starknet: "^7.6.2"
  storybook: "^8.5.0"
  swr: "^2.2.5"
  tailwindcss: "^3.4.3"
  tsup: "^8.0.1"
  typescript: "^5.7.3"
  typescript-eslint: "^8.20.0"
  viem: "^2.21.32"
  vite: "^6.0.0"
  vite-plugin-top-level-await: "^1.4.4"
  vite-plugin-wasm: "^3.4.1"
  vite-tsconfig-paths: "^5.1.4"
  wasm-pack: "^0.13.0"
  "qrcode.react": "^4.2.0"
