packages:
  - examples/next
  - examples/svelte
  - packages/*

catalog:
  "@cartridge/penpal": "^6.2.3"
  "@starknet-io/types-js": "^0.7.7"
  "@starknet-react/chains": "^3.1"
  "@starknet-react/core": "^3.7"
  "@storybook/addon-essentials": "^8.4.7"
  "@storybook/addon-interactions": "^8.4.7"
  "@storybook/addon-links": "^8.4.7"
  "@storybook/addon-themes": "^8.4.7"
  "@storybook/blocks": "^8.4.7"
  "@storybook/react": "^8.4.7"
  "@storybook/react-vite": "^8.4.7"
  "@storybook/test": "^8.4.7"
  "@storybook/test-runner": "^0.21.0"
  "@storybook/theming": "^8.4.7"
  "@types/jest-image-snapshot": "^6.4.0"
  "@types/node": "^20.16.11"
  "@types/react": "^19.0.0"
  "@types/react-dom": "^19.0.3"
  "@vitejs/plugin-react-swc": "^3.5.0"
  autoprefixer: "^10.4.18"
  base64url: "^3.0.1"
  eslint: "^9.12.0"
  fast-deep-equal: "^3.1.3"
  globals: "^15.0.0"
  http-server: "^14.1.1"
  jest-image-snapshot: "^6.4.0"
  playwright: "^1.49.1"
  postcss: "^8.4.35"
  postcss-import: "^16.1.0"
  prettier: "^3.4.2"
  query-string: "^7.1.1"
  react: "^19.0.0"
  react-dom: "^19.0.0"
  react-query: "^3.39.2"
  react-router-dom: "^6.27.0"
  sonner: "^1.4.41"
  start-server-and-test: "^2.0.9"
  starknet: "^6.21.0"
  storybook: "^8.4.7"
  swr: "^2.2.5"
  tailwindcss: "^3.4.3"
  tsup: "^8.0.1"
  typescript: "^5.7.3"
  typescript-eslint: "^8.20.0"
  viem: "^2.21.32"
  vite: "^6.0.7"
  vite-plugin-top-level-await: "^1.4.4"
  vite-plugin-wasm: "^3.4.1"
  wasm-pack: "^0.13.0"
