/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_cartridgeaccount_free(a: number, b: number): void;
export function cartridgeaccount_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number): void;
export function cartridgeaccount_ownerGuid(a: number): number;
export function cartridgeaccount_registerSession(a: number, b: number, c: number, d: number, e: number): number;
export function cartridgeaccount_createSession(a: number, b: number, c: number, d: number): number;
export function cartridgeaccount_estimateInvokeFee(a: number, b: number, c: number, d: number, e: number): number;
export function cartridgeaccount_execute(a: number, b: number, c: number, d: number): number;
export function cartridgeaccount_executeFromOutside(a: number, b: number, c: number, d: number): number;
export function cartridgeaccount_hasSession(a: number, b: number, c: number, d: number): void;
export function cartridgeaccount_sessionJson(a: number, b: number): void;
export function cartridgeaccount_revokeSession(a: number, b: number): void;
export function cartridgeaccount_signMessage(a: number, b: number, c: number): number;
export function cartridgeaccount_deploySelf(a: number, b: number): number;
export function cartridgeaccount_delegateAccount(a: number): number;
export function __wbg_cartridgesessionaccount_free(a: number, b: number): void;
export function cartridgesessionaccount_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function cartridgesessionaccount_new_as_registered(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function cartridgesessionaccount_sign(a: number, b: number, c: number, d: number): number;
export function cartridgesessionaccount_execute(a: number, b: number, c: number): number;
export function cartridgesessionaccount_execute_from_outside(a: number, b: number, c: number): number;
export function __wbg_jscontrollererror_free(a: number, b: number): void;
export function __wbg_get_jscontrollererror_code(a: number): number;
export function __wbg_set_jscontrollererror_code(a: number, b: number): void;
export function __wbg_get_jscontrollererror_message(a: number, b: number): void;
export function __wbg_set_jscontrollererror_message(a: number, b: number, c: number): void;
export function __wbg_get_jscontrollererror_data(a: number, b: number): void;
export function __wbg_set_jscontrollererror_data(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hab75a3c637f96005(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h47b629288504f118(a: number, b: number, c: number, d: number): void;
