export const data = {
  games: [
    {
      icon: "https://raw.githubusercontent.com/cartridge-gg/controller/refs/heads/main/packages/keychain/public/whitelabel/cartridge/icon.svg",
      name: "Cartridge",
      slot: "cartridge",
      namespace: "cartridge",
      points: 400,
    },
    {
      icon: "https://raw.githubusercontent.com/cartridge-gg/controller/refs/heads/main/packages/keychain/public/whitelabel/loot-survivor/icon.png",
      name: "Loot Survivor",
      slot: "lootsurvivor",
      namespace: "lootsurvivor",
      points: 400,
    },
    {
      icon: "https://raw.githubusercontent.com/cartridge-gg/controller/refs/heads/main/packages/keychain/public/whitelabel/jokers-of-neon/icon.png",
      name: "Jockers of Neon",
      slot: "jokersofneon",
      namespace: "jokersofneon",
      points: 400,
    },
    {
      icon: "https://raw.githubusercontent.com/cartridge-gg/controller/refs/heads/main/packages/keychain/public/whitelabel/dope-wars/icon.png",
      name: "Dope Wars",
      slot: "ryomainnet",
      namespace: "dopewars",
      points: 400,
    },
    {
      icon: "https://raw.githubusercontent.com/cartridge-gg/controller/refs/heads/main/packages/keychain/public/whitelabel/eternum/icon.gif",
      name: "Eternum",
      slot: "eternum-rc1-1",
      namespace: "eternum",
      points: 400,
    },
    {
      icon: "https://raw.githubusercontent.com/cartridge-gg/controller/refs/heads/main/packages/keychain/public/whitelabel/blob-arena/icon.png",
      name: "Blob Arena",
      slot: "blobarena",
      namespace: "blobarena",
      points: 400,
    },
    {
      icon: "https://raw.githubusercontent.com/cartridge-gg/controller/refs/heads/main/packages/keychain/public/whitelabel/force-prime/icon.png",
      name: "Force Prime",
      slot: "forceprime",
      namespace: "forceprime",
      points: 400,
    },
    {
      icon: "https://raw.githubusercontent.com/cartridge-gg/controller/refs/heads/main/packages/keychain/public/whitelabel/realm-of-ra/icon.png",
      name: "Realm of Ra",
      slot: "realmofra",
      namespace: "realmofra",
      points: 0,
    },
    {
      icon: "https://raw.githubusercontent.com/cartridge-gg/controller/refs/heads/main/packages/keychain/public/whitelabel/dark-shuffle/icon.svg",
      name: "Dark Shuffle",
      slot: "darkshuffle",
      namespace: "darkshuffle",
      points: 0,
    },
    {
      icon: "https://raw.githubusercontent.com/cartridge-gg/controller/refs/heads/main/packages/keychain/public/whitelabel/pistols/icon.png",
      name: "Pistols",
      slot: "pistols",
      namespace: "pistols",
      points: 0,
    },
    {
      icon: "invalid.png",
      name: "Craft Island",
      slot: "craftisland",
      namespace: "craftisland",
      points: 0,
    },
    {
      icon: "",
      name: "Block Heroes",
      slot: "blockheroes",
      namespace: "blockheroes",
      points: 0,
    },
  ],
};
