export const GATEWAY_MAINNET = process.env.NEXT_PUBLIC_GATEWAY_MAINNET;
export const GATEWAY_GOERLI = process.env.NEXT_PUBLIC_GATEWAY_GOERLI;
export const GATEWAY_GOERLI2 = process.env.NEXT_PUBLIC_GATEWAY_GOERLI2;

export const ETH_RPC_MAINNET = process.env.NEXT_PUBLIC_ETH_RPC_MAINNET;
export const ETH_RPC_GOERLI = process.env.NEXT_PUBLIC_ETH_RPC_GOERLI;
